- type: job
  id: TaipanCommunicationsOfficer
  name: офицер телекоммуникаций
  playTimeTracker: TaipanCommunicationsOfficer
  description: Вы управляете системами связи и координацией информации на станции Тайпан.
  startingGear: TaipanCommunicationsOfficerGear
  icon: "JobIconTaipanCommunicationsOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 60000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 60000
    - !type:DepartmentTimeRequirement
      department: Command
      time: 108000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000
    - !type:OverallPlaytimeRequirement
      time: 360000
    - !type:AgeRequirement
      requiredAge: 26
  access:
  - TaipanCommand
  - TaipanCommunicationsOfficer
  accessGroups:
  - AllAccess

- type: startingGear
  id: TaipanCommunicationsOfficerGear
  equipment:
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesBootsSyndieFilled
    jumpsuit: ClothingUniformJumpsuitTaipanCommunicationsOfficer
    gloves: ClothingHandsGlovesCombat
    id: TaipanCommunicationsOfficerPDA
    back: ClothingBackpackSyndicate
    belt: ClothingBeltAssault