- type: job
  id: TaipanTelecommunicationsOfficer
  name: Офицер телекоммуникаций
  playTimeTracker: TaipanTelecommunicationsOfficer
  description: Вы управляете системами связи и координацией информации на станции Тайпан.
  startingGear: TaipanTelecommunicationsOfficerGear
  icon: "JobIconTaipanTelecommunicationsOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 60000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 60000
    - !type:DepartmentTimeRequirement
      department: Command
      time: 108000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000
    - !type:OverallPlaytimeRequirement
      time: 360000
    - !type:AgeRequirement
      requiredAge: 26
  access:
  - TaipanCommand
  - TaipanCommunicationsOfficer
  accessGroups:
  - AllAccess

- type: startingGear
  id: TaipanTelecommunicationsOfficerGear
  equipment:
    eyes: ClothingEyesHudTaipan
    ears: ClothingHeadsetAltTaipan
    shoes: ClothingShoesDress
    jumpsuit: ClothingUniformJumpsuitTaipanFormal
    gloves: ClothingHandsGlovesWhite
    id: TaipanCommunicationsOfficerPDA
    back: ClothingBackpackStandard
    belt: ClothingBeltUtility
    pocket1: TaipanWhistle
    pocket2: ClothingMaskGasTaipan