- type: job
  id: TaipanCargotech
  name: Карготехник
  playTimeTracker: TaipanCargotech
  description: Вы отвечает за управление грузовыми процессами и доставку по станции.
  startingGear: TaipanCargotechGear
  icon: "JobIconTaipanCargotech"
  supervisors: job-supervisors-quartermaster
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000
    - !type:OverallPlaytimeRequirement
      time: 36000
  access:
  - TaipanMaint
  - TaipanCargo

- type: startingGear
  id: TaipanCargotechGear
  equipment:
    ears: ClothingHeadsetTaipan
    jumpsuit: ClothingUniformJumpsuitTaipanCargotech
    back: ClothingBackpackStandard
    shoes: ClothingShoesBootsTaipan
    id: TaipanCargotechPDA