- type: job
  id: TaipanStationEngineer
  name: ремонтник
  playTimeTracker: TaipanStationEngineer
  description: Вы отвечаете за ремонт и модернизацию инфраструктуры станции Тайпан.
  startingGear: TaipanStationEngineerGear
  icon: "JobIconTaipanStationEngineer"
  supervisors: job-supervisors-chief-engineer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 12000
  access:
  - TaipanBasic
  - TaipanEngineering
  - TaipanMaint

- type: startingGear
  id: TaipanStationEngineerGear
  equipment:
    ears: ClothingHeadsetTaipan
    jumpsuit: ClothingUniformJumpsuitTaipanStationEngineer
    outerClothing: ClothingOuterVestHazard
    shoes: ClothingShoesBootsWork
    id: TaipanStationEngineerPDA
    back: ClothingBackpackEngineering
    belt: ClothingBeltUtilityEngineering